# Documentation: http://docs.travis-ci.com/user/languages/julia/
# This is pinned to LightGBM examples for the relevant version
# This is also pinned to some internal hackery for travis windows setup
language: julia
before_install:
  - wget -O /tmp/lgbm.tar https://github.com/microsoft/LightGBM/archive/v2.3.1.tar.gz
  - tar -xf /tmp/lgbm.tar -C /tmp/
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
os:
  - linux
  - osx
  - windows
env:
  - LIGHTGBM_EXAMPLES_PATH=/tmp/LightGBM-2.3.1
  - LIGHTGBM_EXAMPLES_PATH=C:\\Users\\travis\\AppData\\Local\\Temp\\LightGBM-2.3.1
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
jobs:
  allow_failures:
    - os: osx
  exclude:
    - os: linux
      env:
        - LIGHTGBM_EXAMPLES_PATH=C:\\Users\\travis\\AppData\\Local\\Temp\\LightGBM-2.3.1
    - os: windows
      env:
        - LIGHTGBM_EXAMPLES_PATH=/tmp/LightGBM-2.3.1
    - os: osx
      env:
        - LIGHTGBM_EXAMPLES_PATH=C:\\Users\\travis\\AppData\\Local\\Temp\\LightGBM-2.3.1
